/**
 * Hand-entered expected scores (declarer's side; negative = down).
 * [contract, declarerVulnerable, tricks relative to contract (0 = made), expected]
 * Entered from the published duplicate scoring table, NOT generated by the code.
 * !! Have a human spot-check these against the official WBF/ACBL scoring chart. !!
 */
export type Known = [contract: string, vul: boolean, rel: number, expected: number];

// Made exactly, not vulnerable.
const NV: Array<[string, number]> = [
  ["1C", 70], ["1D", 70], ["1H", 80], ["1S", 80], ["1NT", 90],
  ["2C", 90], ["2D", 90], ["2H", 110], ["2S", 110], ["2NT", 120],
  ["3C", 110], ["3D", 110], ["3H", 140], ["3S", 140], ["3NT", 400],
  ["4C", 130], ["4D", 130], ["4H", 420], ["4S", 420], ["4NT", 430],
  ["5C", 400], ["5D", 400], ["5H", 450], ["5S", 450], ["5NT", 460],
  ["6C", 920], ["6D", 920], ["6H", 980], ["6S", 980], ["6NT", 990],
  ["7C", 1440], ["7D", 1440], ["7H", 1510], ["7S", 1510], ["7NT", 1520],
];
// Made exactly, vulnerable.
const V: Array<[string, number]> = [
  ["1C", 70], ["1NT", 90], ["2H", 110], ["3H", 140], ["3NT", 600],
  ["4C", 130], ["4H", 620], ["4S", 620], ["4NT", 630],
  ["5C", 600], ["5D", 600], ["5H", 650], ["5NT", 660],
  ["6C", 1370], ["6D", 1370], ["6H", 1430], ["6S", 1430], ["6NT", 1440],
  ["7C", 2140], ["7H", 2210], ["7S", 2210], ["7NT", 2220],
];

export const KNOWN: Known[] = [
  ...NV.map(([c, e]): Known => [c, false, 0, e]),
  ...V.map(([c, e]): Known => [c, true, 0, e]),

  // Overtricks, undoubled
  ["3NT", false, 1, 430], ["3NT", false, 2, 460], ["4S", false, 1, 450], ["4S", false, 2, 480],
  ["5C", false, 1, 420], ["5C", false, 2, 440], ["1NT", false, 1, 120], ["1NT", false, 2, 150],
  ["1H", false, 3, 170], ["2D", false, 2, 130], ["6NT", false, 1, 1020],
  ["3NT", true, 1, 630], ["4H", true, 1, 650], ["4H", true, 2, 680], ["5D", true, 1, 620],
  ["6H", true, 1, 1460], ["6C", true, 1, 1390],

  // Doubled, made
  ["1SX", false, 0, 160], ["1CX", false, 0, 140], ["1NTX", false, 0, 180], ["2CX", false, 0, 180],
  ["2HX", false, 0, 470], ["3CX", false, 0, 470], ["4CX", false, 0, 510], ["3NTX", false, 0, 550],
  ["4HX", false, 0, 590], ["6SX", false, 0, 1210], ["7NTX", false, 0, 1790],
  ["1NTX", false, 1, 280], ["2SX", false, 2, 670], ["4SX", false, 1, 690],
  ["1SX", true, 0, 160], ["1NTX", true, 0, 180], ["1NTX", true, 1, 380], ["2HX", true, 0, 670],
  ["3NTX", true, 0, 750], ["4HX", true, 0, 790], ["4HX", true, 1, 990], ["2SX", true, 2, 1070],
  ["6SX", true, 0, 1660], ["7NTX", true, 0, 2490],

  // Redoubled, made
  ["1SXX", false, 0, 520], ["1CXX", false, 0, 230], ["1NTXX", false, 0, 560], ["2CXX", false, 0, 560],
  ["4HXX", false, 0, 880], ["1SXX", false, 1, 720], ["7NTXX", false, 0, 2280],
  ["1SXX", true, 0, 720], ["4HXX", true, 0, 1080], ["1SXX", true, 1, 1120], ["6NTXX", true, 0, 2110],

  // Undoubled down: 50/trick nonvul, 100/trick vul
  ["4S", false, -1, -50], ["4S", false, -2, -100], ["4S", false, -3, -150],
  ["4S", true, -1, -100], ["4S", true, -2, -200], ["4S", true, -3, -300],
  ["7NT", false, -13, -650], ["7NT", true, -13, -1300],
  ["3NT", false, -4, -200], ["3NT", true, -4, -400],
];

// Doubled / redoubled undertricks, from the official table. Index i = (i+1) down.
const DOWN_TABLE: Record<string, { nv: number[]; v: number[] }> = {
  X: {
    nv: [100, 300, 500, 800, 1100, 1400, 1700, 2000, 2300, 2600, 2900, 3200, 3500],
    v: [200, 500, 800, 1100, 1400, 1700, 2000, 2300, 2600, 2900, 3200, 3500, 3800],
  },
  XX: {
    nv: [200, 600, 1000, 1600, 2200, 2800, 3400, 4000, 4600, 5200, 5800, 6400, 7000],
    v: [400, 1000, 1600, 2200, 2800, 3400, 4000, 4600, 5200, 5800, 6400, 7000, 7600],
  },
};
for (const dbl of ["X", "XX"] as const) {
  for (const n of [1, 2, 3, 4, 5, 6, 7, 8, 10, 13]) {
    KNOWN.push([`7NT${dbl}`, false, -n, -DOWN_TABLE[dbl]!.nv[n - 1]!]);
    KNOWN.push([`7NT${dbl}`, true, -n, -DOWN_TABLE[dbl]!.v[n - 1]!]);
  }
}
// Same penalties for a smaller contract (down is independent of level/denomination).
KNOWN.push(["4SX", false, -3, -500], ["4SX", true, -3, -800], ["2HXX", false, -2, -600], ["3NTX", true, -1, -200]);
